export const deckPageConfigs = [
  {
    id: 0,
    title: "Dashboard",
    pageIndex: 0,
    visible: true,
    iconName: "Squares2X2Icon",
  },
  {
    id: 1,
    title: "Deal Overview",
    pageIndex: 1,
    visible: true,
    iconName: "QueueListIcon",
  },
  {
    id: 2,
    title: "The Property",
    pageIndex: 2,
    visible: true,
    iconName: "BuildingOfficeIcon",
  },
  {
    id: 3,
    title: "The Market",
    pageIndex: 3,
    visible: true,
    iconName: "MapPinIcon",
  },
  {
    id: 4,
    title: "Business Plan",
    pageIndex: 4,
    visible: true,
    iconName: "CubeTransparentIcon",
  },
  {
    id: 5,
    title: "Financials",
    pageIndex: 5,
    visible: true,
    iconName: "ChartBarIcon",
  },
  {
    id: 6,
    title: "Comps",
    pageIndex: 6,
    visible: true,
    iconName: "GlobeAsiaAustraliaIcon",
  },
  {
    id: 7,
    title: "Sponsorship",
    pageIndex: 7,
    visible: true,
    iconName: "UsersIcon",
  },
];
