import {
  Bars3Icon,
  Squares2X2Icon,
  QueueListIcon,
  BuildingOfficeIcon,
  MapPinIcon,
  CubeTransparentIcon,
  ChartBarIcon,
  GlobeAsiaAustraliaIcon,
  UsersIcon,
} from "@heroicons/react/24/solid";

export const deckPageConfigs = [
  {
    id: 0,
    title: "Dashboard",
    pageIndex: 0,
    visible: true,
    icon: Squares2X2Icon,
  },
  {
    id: 1,
    title: "Deal Overview",
    pageIndex: 1,
    visible: true,
    icon: QueueListIcon,
  },
  {
    id: 2,
    title: "The Property",
    pageIndex: 2,
    visible: true,
    icon: BuildingOfficeIcon,
  },
  {
    id: 3,
    title: "The Market",
    pageIndex: 3,
    visible: true,
    icon: MapPinIcon,
  },
  {
    id: 4,
    title: "Business Plan",
    pageIndex: 4,
    visible: true,
    icon: CubeTransparentIcon,
  },
  {
    id: 5,
    title: "Financials",
    pageIndex: 5,
    visible: true,
    icon: ChartBarIcon,
  },
  {
    id: 6,
    title: "Comps",
    pageIndex: 6,
    visible: true,
    icon: GlobeAsiaAustraliaIcon,
  },
  {
    id: 7,
    title: "Sponsorship",
    pageIndex: 7,
    visible: true,
    icon: UsersIcon,
  },
];
