export enum WidgetEnum {
  FRAME = "FRAME",
  NONE = "NONE",
}

export enum WidgetElement {
  PICTURE = "PICTURE",
  VIDEO = "VIDEO",
  TABLE = "TABLE",
  CHART = "CHART",
  PIE_CHART = "PIE_CHART",
  ICON_GALLERY = "ICON_GALLERY",
  GALLERY = "GALLERY",
  TIMELINE = "TIMELINE",
  SIMPLE_LIST = "SIMPLE_LIST",
  COMPLEX_LIST = "COMPLEX_LIST",
  SPREADSHEET = "SPREADSHEET",
  MAP = "MAP",
  IFRAME = "IFRAME",
  CONTACT_CARD = "CONTACT_CARD",
  CALENDLY = "CALENDLY",
  IFRAME = "IFRAME",
  NONE = "NONE",
}
