export enum WidgetEnum {
  FRAME = "FRAME",
  NONE = "NONE",
}

export enum WidgetElement {
  PICTURE = "PICTURE",
  VIDEO = "VIDEO",
  GALLERY = "GALLERY",
  SIMPLE_LIST = "SIMPLE_LIST",
  TABS = "TABS",
  COMPLEX_LIST = "COMPLEX_LIST",
  SPREADSHEET = "SPREADSHEET",
  MAP = "MAP",
  ICON_GALLERY = "ICON_GALLERY",
  IFRAME = "IFRAME",
  APP = "APP",
  BUTTON = "BUTTON",
  TIMELINE = "TIMELINE",
  COMPS = "COMPS",
  CONTACT_CARD = "CONTACT_CARD",
  NONE = "NONE",
  TABLE = "TABLE",
  CHART = "CHART",
  PIE_CHART = "PIE_CHART",
}
